### ISSUE TITLE
[enhancement request] increase significant digits for percentage?

### ISSUE THREAD

**Issue by blysik** [NatelEnergy/grafana-discrete-panel#1]
First, awesome panel!  I approximated something like this before with the built in panels, but your panel is way easier.

Enhancement request:  I plot 7 days worth of 1s and 0s of service availability.  It would be great if I could have percentages shown with more significant digits.  ie, to try and show five 9s of availability.  It looks like it's rounded up currently to 99% or 100%.  Nothing in between.  

Thanks!

**Comment by royemmerich** [comment]
This screenshot is another example where additional precision is required. BMS balancer 692 was open for just a few minutes during the last 24 hour period but instead of 0.X%, just 0% is shown as the amount of time it was open.

![screen shot 2017-05-15 at 22 24 52](https://cloud.githubusercontent.com/assets/3904395/26077735/704220ca-39bd-11e7-8e2b-1cdfdd112558.png)

**Comment by ryantxu** [comment]
fixed in next release v0.0.5

There is a new config to set it explicitly, or it will show more digits for very small or close to 100 percentages
