### ISSUE TITLE
Keep dist folder

### ISSUE THREAD

**Issue by miton18** [NatelEnergy/grafana-discrete-panel#70]
Hi ! We just upgrade the plugins to the b7ff0d195dce12fc1892e88cc415e1ac44dc02e3 version, which broke all the graphs.
We will now, (yarn) build the plugin before deploy it on the prod.

Just a question, why did you choose to remove the __dist__ folder from the repository when Grafana developer guide ask to let it ?

http://docs.grafana.org/plugins/developing/development/#buildscript

**Comment by ryantxu** [comment]
The dist folder makes it difficult to develop the plugin since every commit can easily conflict.   Also the pull request I get tend to include the dist folder :( so they can not be easily merged.

If you want a pre-build version, you can find it from the latest circle CI build:

![ddd](https://user-images.githubusercontent.com/705951/46693661-516ba000-cbbf-11e8-8906-0b6aec5828f2.png)
